source 'https://github.com/CocoaPods/Specs.git'
platform :ios, 7.1
xcodeproj 'EssentialTips.xcodeproj'
inhibit_all_warnings!
#link_with ['DataParenting', 'DataParentingDev', 'DataParentingTests']

#pod 'OpenSSL', ' 1.0.200' # 1.0.201 does not compile!
pod 'MBProgressHUD', '~> 0.8'
pod 'SWTableViewCell', '0.3.4'
pod 'Heap', '2.1.3'
pod 'Parse+NSCoding', :git => 'https://github.com/npahucki/Parse-NSCoding.git', :commit => '7ca144edd756eafa4f8bd95fbdfca86bfdd7898a'
pod 'Parse', '1.7.1'
pod 'ParseFacebookUtils', '1.7.1'
pod 'ParseUI', '1.1.3'
pod 'PFCloud+Cache', :git => 'https://github.com/npahucki/PFCloud-Cache.git', :commit => '4a909d495c120fc5456d4ed9349fecabece684c6'
pod 'UIActionSheet+Blocks'
pod 'AppsFlyer-SDK', '2.5.3.11.1'
pod 'Mixpanel', '2.7.2'
pod 'CMPopTipView', '2.2'






